name: MyST Install Action
description: Install Node, MyST, and other dependencies
inputs:
  node:
    description: 'Node version to install'
    required: true
    default: '18'
runs:
  using: 'composite'
  steps:
    - name: Install libxml
      run: |
        sudo apt-get update
        sudo apt-get install -y libxml2-utils
      shell: bash
    - name: Setup Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node }}
        cache: 'npm'
    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: '.github/requirements/requirements-execute.txt'
    - name: Install execution requirements for ipykernel and jupyter-server
      run: python -m pip install -r .github/requirements/requirements-execute.txt
      shell: bash
    - name: Install node deps and build Myst
      run: |
        npm install
        npm run build
      shell: bash
