// Frontmatter and Site/Project Configs
//
// loaded directly from curvenote.yml

export type Frontmatter = {
  description?: string;
};

export type ProjectConfig = Frontmatter & {
  index?: string;
  exclude?: string[];
};

export type SiteProject = {
  path: string;
  slug: string;
};

export type SiteNavPage = {
  title: string;
  url: string;
};

export type SiteNavFolder = {
  title: string;
  children: SiteNavItem[];
};

export type SiteNavItem = SiteNavPage | SiteNavFolder;

export type SiteAction = SiteNavPage & {
  static: boolean;
};

export type SiteConfig = Frontmatter & {
  title?: string;
  twitter?: string;
  domains: string[];
  logo?: string;
  logoText?: string;
  projects: SiteProject[];
  nav: SiteNavItem[];
  actions: SiteAction[];
};

export type Config = {
  version: 1;
  project?: ProjectConfig;
  site?: SiteConfig;
};

// Types for local Project
//
// Files are local paths relative to the current directory.
// These are autogenerated based on curvenote.yml

export type pageLevels = 1 | 2 | 3 | 4 | 5 | 6;

export type LocalProjectFolder = {
  title: string;
  level: pageLevels;
};

export type LocalProjectPage = {
  file: string;
  slug: string;
} & LocalProjectFolder;

export type LocalProject = {
  path: string;
  file: string;
  index: string;
  title: string;
  pages: (LocalProjectPage | LocalProjectFolder)[];
};

// Manifest shipped with site content
//
// Combines info from config, local project.
// Removes local path info

export type ManifestProjectFolder = {
  title: string;
  level: pageLevels;
};

export type ManifestProjectPage = {
  slug: string;
} & ManifestProjectFolder;

export type ManifestProject = Frontmatter & {
  slug: string;
  index: string;
  title: string;
  pages: (ManifestProjectPage | ManifestProjectFolder)[];
};

export type SiteManifest = {
  title: string;
  twitter?: string;
  logo?: string;
  logoText?: string;
  nav: SiteNavItem[];
  actions: SiteAction[];
  projects: ManifestProject[];
};
