name: Apply Pull Request Labels
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize, reopened]
jobs:
  auto-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
      issues: write
    steps:
      - name: Checkout contents
        uses: actions/checkout@v4
      - name: Add labels
        uses: actions/labeler@v6
