name: Apply Pull Request Labels
on:
  pull_request_target:
    types: [opened, labeled, unlabeled, synchronize, reopened]
jobs:
  auto-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      # As this is a pull_request_target, we'll get `main` here
      - name: Checkout contents
        uses: actions/checkout@v4
      - name: Add labels
        uses: actions/labeler@v6
