name: CI

on:
  push:
    branches: [main, ci-*]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          submodules: recursive
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - name: Check formatting (style rules etc)
        run: bun run lint:format
      - name: Run linter (code correctness etc)
        run: bun run lint
      - name: Check for circular dependencies
        run: bun run lint:circular
      - name: Ensure changeset has the right structure and doesn't contain ignored packages
        run: bun run version
  test:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    name: Testing
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          submodules: recursive
      - uses: ./.github/actions/install
      - name: Run tests
        run: bun run test
  # This is just an additional check to make sure the build passes with our docs
  docs:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    name: Running test docs build
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install myst
        uses: ./.github/actions/install
      - name: Install docs dependencies
        run: |
          pip install -r docs/requirements.txt
      - name: Build docs
        run: |
          cd docs
          myst build --html --execute
