name: Pull Request Labels
on:
  pull_request_target:
    types: [opened, labeled, unlabeled, synchronize, reopened]
jobs:
  require-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: |
            enhancement
            bug
            documentation
            maintenance
            release
  label-release:
    runs-on: ubuntu-latest
    # if: github.event.action == 'opened' && github.head_ref == "changeset-release/main"
    permissions:
      pull-requests: write
      contents: read
      issues: write
    steps:
      - run: echo ${{ github.event.action == 'opened' && github.head_ref == 'changeset-release/main' }}
      - name: Label release pull request
        # .github/labeler.yml defines configuration
        uses: actions/labeler@v5
